bot: change signature of notAuthorized function
From Promise<void> to Promise<undefined>, to get rid of the
following error:
```
tests/bot/validation.spec.ts(376,19): error TS2339: Property 'tg_id' does not exist on type 'void | (UserDocument & { _id: ObjectId; })'.
  Property 'tg_id' does not exist on type 'void'.
```