Typescript support: first step (#392)
* bot/start,jobs/pending_payments: convert js to ts

Empty tsconfig.json file is added so that we can compile all ts
files using tsc command.

Co-authored-by: Parham <parhaamsaremi@gmail.com>

* Add strict to tsconfig.json

* Add `pre` hook for some `npm run` commands

We need to compile TypeScript files before running the code.

* Update dependencies

The typescript package is required. Also we need the latest
version of @types/node, otherwise we get this error we run
the `npm start` & `npm run dev` commands:

```
~\projs\bot ❯ npm start

> lnp2pbot@0.8.1 prestart
> tsc

node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

72 declare var AbortSignal: {
               ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:2304:13
    2304 declare var AbortSignal: {
                     ~~~~~~~~~~~
    'AbortSignal' was also declared here.

Found 1 error in node_modules/@types/node/globals.d.ts:72
```

---------

Co-authored-by: Parham <parhaamsaremi@gmail.com>
Co-authored-by: Mersho <code.rezaei@gmail.com>